# Use full .NET SDK (needed for EF tools)
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release

# Copy local tool manifest
COPY ../.config/dotnet-tools.json .config/dotnet-tools.json

# Restore local tools
RUN dotnet tool restore

WORKDIR /app
COPY ["API/API.csproj", "API/"]
RUN dotnet restore "API/API.csproj"
COPY . .
WORKDIR "/app/API"
RUN dotnet build "./API.csproj" -c $BUILD_CONFIGURATION -o /app/build
ENTRYPOINT ["/bin/bash"] # Set default command to bash