// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116151759_UltraSuperDbV5")]
    partial class UltraSuperDbV5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Records.Entities.AssetFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CdnPath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cdn_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_asset_files");

                    b.ToTable("asset_files");
                });

            modelBuilder.Entity("Domain.Records.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("case_number");

                    b.Property<Guid>("CommissionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("commission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("IncidentDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("incident_date_time");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("location_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_cases");

                    b.HasIndex("CommissionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_cases_commission_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("i_x_cases_department_id");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasDatabaseName("i_x_cases_location_id");

                    b.ToTable("cases");
                });

            modelBuilder.Entity("Domain.Records.Entities.CaseOfficer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("officer_id");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_case_officers");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("i_x_case_officers_case_id");

                    b.HasIndex("OfficerId")
                        .HasDatabaseName("i_x_case_officers_officer_id");

                    b.ToTable("case_officers");
                });

            modelBuilder.Entity("Domain.Records.Entities.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmployedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employed_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_commissions");

                    b.ToTable("commissions");
                });

            modelBuilder.Entity("Domain.Records.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("service");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_departments");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("Domain.Records.Entities.FileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id");

                    b.Property<string>("CdnPath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cdn_path");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hash");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_favorite");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_file_records");

                    b.ToTable("file_records");
                });

            modelBuilder.Entity("Domain.Records.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsBlurry")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_blurry");

                    b.Property<bool>("IsEmbedded")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_embedded");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_hidden");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_images");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("i_x_images_file_id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("Domain.Records.Entities.ImageObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<bool?>("HumanApproved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("human_approved");

                    b.Property<bool>("HumanReviewed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("human_reviewed");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("char(36)")
                        .HasColumnName("image_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload_json");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("p_k_image_observations");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("i_x_image_observations_image_id");

                    b.ToTable("image_observations");
                });

            modelBuilder.Entity("Domain.Records.Entities.InvolvedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload_json");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_involved_entities");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("i_x_involved_entities_case_id");

                    b.ToTable("involved_entities");
                });

            modelBuilder.Entity("Domain.Records.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("municipality");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("street");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_locations");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("Domain.Records.Entities.Marker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<decimal>("EastRd")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("east_rd");

                    b.Property<decimal?>("HeightRd")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("height_rd");

                    b.Property<Guid>("IconId")
                        .HasColumnType("char(36)")
                        .HasColumnName("icon_id");

                    b.Property<decimal>("NorthRd")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("north_rd");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_markers");

                    b.HasIndex("IconId")
                        .HasDatabaseName("i_x_markers_icon_id");

                    b.ToTable("markers");
                });

            modelBuilder.Entity("Domain.Records.Entities.MarkerIcon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int?>("AssociatedEntityType")
                        .HasColumnType("int")
                        .HasColumnName("associated_entity_type");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IconId")
                        .HasColumnType("char(36)")
                        .HasColumnName("icon_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_marker_icons");

                    b.HasIndex("IconId")
                        .HasDatabaseName("i_x_marker_icons_icon_id");

                    b.ToTable("marker_icons");
                });

            modelBuilder.Entity("Domain.Records.Entities.Officer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("department_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("team");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_officers");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("i_x_officers_department_id");

                    b.ToTable("officers");
                });

            modelBuilder.Entity("Domain.Records.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_templates");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("i_x_templates_department_id");

                    b.ToTable("templates");
                });

            modelBuilder.Entity("Domain.Records.Entities.TemplateVar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_template_vars");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("i_x_template_vars_case_id");

                    b.ToTable("template_vars");
                });

            modelBuilder.Entity("Domain.Records.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<Guid>("OfficerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("officer_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("OfficerId")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_officer_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Domain.Records.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_roles_user_id");

                    b.ToTable("user_roles");
                });

            modelBuilder.Entity("FileRecordInvolvedEntity", b =>
                {
                    b.Property<Guid>("AssociatedEntitiesId")
                        .HasColumnType("char(36)")
                        .HasColumnName("associated_entities_id");

                    b.Property<Guid>("AssociatedFilesId")
                        .HasColumnType("char(36)")
                        .HasColumnName("associated_files_id");

                    b.HasKey("AssociatedEntitiesId", "AssociatedFilesId")
                        .HasName("p_k_file_record_involved_entity");

                    b.HasIndex("AssociatedFilesId")
                        .HasDatabaseName("i_x_file_record_involved_entity_associated_files_id");

                    b.ToTable("file_record_involved_entity");
                });

            modelBuilder.Entity("FileRecordMarker", b =>
                {
                    b.Property<Guid>("AssociatedFilesId")
                        .HasColumnType("char(36)")
                        .HasColumnName("associated_files_id");

                    b.Property<Guid>("AssociatedMarkersId")
                        .HasColumnType("char(36)")
                        .HasColumnName("associated_markers_id");

                    b.HasKey("AssociatedFilesId", "AssociatedMarkersId")
                        .HasName("p_k_file_record_marker");

                    b.HasIndex("AssociatedMarkersId")
                        .HasDatabaseName("i_x_file_record_marker_associated_markers_id");

                    b.ToTable("file_record_marker");
                });

            modelBuilder.Entity("InvolvedEntityMarker", b =>
                {
                    b.Property<Guid>("AssociatedEntitiesId")
                        .HasColumnType("char(36)")
                        .HasColumnName("associated_entities_id");

                    b.Property<Guid>("AssociatedMarkersId")
                        .HasColumnType("char(36)")
                        .HasColumnName("associated_markers_id");

                    b.HasKey("AssociatedEntitiesId", "AssociatedMarkersId")
                        .HasName("p_k_involved_entity_marker");

                    b.HasIndex("AssociatedMarkersId")
                        .HasDatabaseName("i_x_involved_entity_marker_associated_markers_id");

                    b.ToTable("involved_entity_marker");
                });

            modelBuilder.Entity("Domain.Records.Entities.Case", b =>
                {
                    b.HasOne("Domain.Records.Entities.Commission", "Commission")
                        .WithOne("Case")
                        .HasForeignKey("Domain.Records.Entities.Case", "CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_cases__commissions_commission_id");

                    b.HasOne("Domain.Records.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_cases__departments_department_id");

                    b.HasOne("Domain.Records.Entities.Location", "Location")
                        .WithOne("Case")
                        .HasForeignKey("Domain.Records.Entities.Case", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_cases__locations_location_id");

                    b.Navigation("Commission");

                    b.Navigation("Department");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Records.Entities.CaseOfficer", b =>
                {
                    b.HasOne("Domain.Records.Entities.Case", "Case")
                        .WithMany("Officers")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_case_officers_cases_case_id");

                    b.HasOne("Domain.Records.Entities.Officer", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_case_officers__officers_officer_id");

                    b.Navigation("Case");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("Domain.Records.Entities.Image", b =>
                {
                    b.HasOne("Domain.Records.Entities.FileRecord", "File")
                        .WithOne("Image")
                        .HasForeignKey("Domain.Records.Entities.Image", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_images_file_records_file_id");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Domain.Records.Entities.ImageObservation", b =>
                {
                    b.HasOne("Domain.Records.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_image_observations_images_image_id");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Domain.Records.Entities.InvolvedEntity", b =>
                {
                    b.HasOne("Domain.Records.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_involved_entities_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Domain.Records.Entities.Marker", b =>
                {
                    b.HasOne("Domain.Records.Entities.MarkerIcon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_markers__marker_icons_icon_id");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("Domain.Records.Entities.MarkerIcon", b =>
                {
                    b.HasOne("Domain.Records.Entities.AssetFile", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_marker_icons_asset_files_icon_id");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("Domain.Records.Entities.Officer", b =>
                {
                    b.HasOne("Domain.Records.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_officers_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Records.Entities.Template", b =>
                {
                    b.HasOne("Domain.Records.Entities.Department", "Department")
                        .WithMany("Templates")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_templates_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Records.Entities.TemplateVar", b =>
                {
                    b.HasOne("Domain.Records.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_template_vars_cases_case_id");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Domain.Records.Entities.User", b =>
                {
                    b.HasOne("Domain.Records.Entities.Officer", "Officer")
                        .WithOne("User")
                        .HasForeignKey("Domain.Records.Entities.User", "OfficerId")
                        .HasConstraintName("f_k_users_officers_officer_id");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("Domain.Records.Entities.UserRole", b =>
                {
                    b.HasOne("Domain.Records.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_roles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FileRecordInvolvedEntity", b =>
                {
                    b.HasOne("Domain.Records.Entities.InvolvedEntity", null)
                        .WithMany()
                        .HasForeignKey("AssociatedEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_file_record_involved_entity_involved_entities_associated_ent~");

                    b.HasOne("Domain.Records.Entities.FileRecord", null)
                        .WithMany()
                        .HasForeignKey("AssociatedFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_file_record_involved_entity_file_records_associated_files_id");
                });

            modelBuilder.Entity("FileRecordMarker", b =>
                {
                    b.HasOne("Domain.Records.Entities.FileRecord", null)
                        .WithMany()
                        .HasForeignKey("AssociatedFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_file_record_marker_file_records_associated_files_id");

                    b.HasOne("Domain.Records.Entities.Marker", null)
                        .WithMany()
                        .HasForeignKey("AssociatedMarkersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_file_record_marker_markers_associated_markers_id");
                });

            modelBuilder.Entity("InvolvedEntityMarker", b =>
                {
                    b.HasOne("Domain.Records.Entities.InvolvedEntity", null)
                        .WithMany()
                        .HasForeignKey("AssociatedEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_involved_entity_marker_involved_entities_associated_entities~");

                    b.HasOne("Domain.Records.Entities.Marker", null)
                        .WithMany()
                        .HasForeignKey("AssociatedMarkersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_involved_entity_marker_markers_associated_markers_id");
                });

            modelBuilder.Entity("Domain.Records.Entities.Case", b =>
                {
                    b.Navigation("Officers");
                });

            modelBuilder.Entity("Domain.Records.Entities.Commission", b =>
                {
                    b.Navigation("Case")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Records.Entities.Department", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Domain.Records.Entities.FileRecord", b =>
                {
                    b.Navigation("Image");
                });

            modelBuilder.Entity("Domain.Records.Entities.Location", b =>
                {
                    b.Navigation("Case")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Records.Entities.Officer", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
